[development.databases]
postgres = { url = "postgres://postgres:postgres@localhost:5432/iot_ruststack_demo" }

[staging]
port = 8000

[staging.databases]
postgres = { url = "postgres://postgres:postgres@localhost:5432/iot_ruststack_demo" }

